
services:
  db:
    image: postgres:16
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    # comment out ports if you don’t want host access
    # ports:
    #   - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: ./web
    container_name: my_webapp
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydb
    depends_on:
      - db

volumes:
  db_data:
